// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {subscription} from '../models';
import {main} from '../models';
import {profile} from '../models';
import {config} from '../models';
import {settings} from '../models';

export function ActivateConfig(arg1:string):Promise<void>;

export function ActivateProfile(arg1:string):Promise<void>;

export function AddSubscription(arg1:string,arg2:string):Promise<subscription.Item>;

export function CheckForUpdates():Promise<main.UpdateCheckResult>;

export function CloseAllConnections():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function Connect():Promise<void>;

export function CreateProfile(arg1:string):Promise<profile.Profile>;

export function DelayTest(arg1:string):Promise<Record<string, any>>;

export function DelayTestGroup(arg1:string):Promise<Record<string, any>>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadConfigFromURL(arg1:string):Promise<main.ConfigEntry>;

export function ExportConfigToFile():Promise<void>;

export function GetActiveConfigID():Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConfig():Promise<string>;

export function GetConfigContent(arg1:string):Promise<string>;

export function GetConfigProxies(arg1:string):Promise<config.ProxyPreviewResult>;

export function GetConfigRulesPage(arg1:number,arg2:number,arg3:string):Promise<main.RulesPageResult>;

export function GetConfigs():Promise<Record<string, any>>;

export function GetConnections():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetProxies():Promise<Record<string, any>>;

export function GetRules():Promise<Record<string, any>>;

export function GetSettings():Promise<settings.Settings>;

export function GetStatus():Promise<main.Status>;

export function GetTraffic():Promise<main.TrafficStats>;

export function ImportConfigAsNew():Promise<main.ConfigEntry>;

export function ImportConfigFromFile():Promise<string>;

export function ListConfigs():Promise<Array<main.ConfigEntry>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListSubscriptions():Promise<Array<subscription.Item>>;

export function OpenHelpDocs():Promise<void>;

export function OpenWebsite():Promise<void>;

export function PatchMode(arg1:string):Promise<void>;

export function RefreshAllConfigs():Promise<void>;

export function RefreshConfigFromURL(arg1:string):Promise<void>;

export function RemoveSubscription(arg1:string):Promise<void>;

export function RenameConfig(arg1:string,arg2:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveConfigContent(arg1:string,arg2:string):Promise<void>;

export function SaveProfileContent(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SelectConfig(arg1:string):Promise<void>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function SetAllowLan(arg1:boolean):Promise<void>;

export function SetLaunchAtLogin(arg1:boolean):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function SetTunEnabled(arg1:boolean):Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;

export function TestConfig(arg1:string):Promise<void>;

export function UpdateAllSubscriptions():Promise<void>;

export function UpdateSubscription(arg1:string):Promise<string>;
