// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateConfig(arg1) {
  return window['go']['main']['App']['ActivateConfig'](arg1);
}

export function ActivateProfile(arg1) {
  return window['go']['main']['App']['ActivateProfile'](arg1);
}

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DelayTest(arg1) {
  return window['go']['main']['App']['DelayTest'](arg1);
}

export function DelayTestGroup(arg1) {
  return window['go']['main']['App']['DelayTestGroup'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadConfigFromURL(arg1) {
  return window['go']['main']['App']['DownloadConfigFromURL'](arg1);
}

export function ExportConfigToFile() {
  return window['go']['main']['App']['ExportConfigToFile']();
}

export function GetActiveConfigID() {
  return window['go']['main']['App']['GetActiveConfigID']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigContent(arg1) {
  return window['go']['main']['App']['GetConfigContent'](arg1);
}

export function GetConfigProxies(arg1) {
  return window['go']['main']['App']['GetConfigProxies'](arg1);
}

export function GetConfigRulesPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetConfigRulesPage'](arg1, arg2, arg3);
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProxies() {
  return window['go']['main']['App']['GetProxies']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTraffic() {
  return window['go']['main']['App']['GetTraffic']();
}

export function ImportConfigAsNew() {
  return window['go']['main']['App']['ImportConfigAsNew']();
}

export function ImportConfigFromFile() {
  return window['go']['main']['App']['ImportConfigFromFile']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function OpenHelpDocs() {
  return window['go']['main']['App']['OpenHelpDocs']();
}

export function OpenWebsite() {
  return window['go']['main']['App']['OpenWebsite']();
}

export function PatchMode(arg1) {
  return window['go']['main']['App']['PatchMode'](arg1);
}

export function RefreshAllConfigs() {
  return window['go']['main']['App']['RefreshAllConfigs']();
}

export function RefreshConfigFromURL(arg1) {
  return window['go']['main']['App']['RefreshConfigFromURL'](arg1);
}

export function RemoveSubscription(arg1) {
  return window['go']['main']['App']['RemoveSubscription'](arg1);
}

export function RenameConfig(arg1, arg2) {
  return window['go']['main']['App']['RenameConfig'](arg1, arg2);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveConfigContent(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigContent'](arg1, arg2);
}

export function SaveProfileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileContent'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectConfig(arg1) {
  return window['go']['main']['App']['SelectConfig'](arg1);
}

export function SelectProxy(arg1, arg2) {
  return window['go']['main']['App']['SelectProxy'](arg1, arg2);
}

export function SetAllowLan(arg1) {
  return window['go']['main']['App']['SetAllowLan'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function SetTunEnabled(arg1) {
  return window['go']['main']['App']['SetTunEnabled'](arg1);
}

export function StartCore() {
  return window['go']['main']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function TestConfig(arg1) {
  return window['go']['main']['App']['TestConfig'](arg1);
}

export function UpdateAllSubscriptions() {
  return window['go']['main']['App']['UpdateAllSubscriptions']();
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
